/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Chef;

import Dbconnect.Connect;
import EntityPackage.Chef;
import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author BhANu
 */
public class Internal_Chef_View_Items extends javax.swing.JInternalFrame {

    /**
     * Creates new form Internal_Chef_View_Items
     */
    
    String key;
    Chef che ;
    public Internal_Chef_View_Items() {
          initComponents();
          
    } 
     public Internal_Chef_View_Items(Chef che1) {
          this();
          che=che1;
          viewItemquery();
    } 
    //method to get the query result from db for items
     public void viewItemquery(){ 
      try{
            item.setModel(DbUtils.resultSetToTableModel(che.viewItems()));
        
         che.viewItems().close();
         Connect.connectToDb().close();
        
       
      }
      catch(SQLException e){
        JOptionPane.showMessageDialog(this,"SQL exception occured" + e);
      }
      
       }
     
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        item = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        searchkey = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        item.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "item_no", "name", "item_type", "cost", "quantity", "status", "description"
            }
        ));
        item.setGridColor(new java.awt.Color(51, 153, 255));
        item.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane2.setViewportView(item);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Items");

        searchkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchkeyActionPerformed(evt);
            }
        });

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 516, Short.MAX_VALUE)
                        .addComponent(searchkey, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(86, 86, 86))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchkey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         
        key=searchkey.getText();
         
        try{
            //add the details to the table by calling the method from the chef class
           item.setModel(DbUtils.resultSetToTableModel(che.Search("items",key)));
       
            //close resultset and connection
            che.Search("items",key).close();
            Connect.connectToDb().close();
             //  che.vw_stat.close();
            }
            catch(Exception e){
        
            }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchkeyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable item;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField searchkey;
    // End of variables declaration//GEN-END:variables
}
