/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Customer;

import EntityPackage.Customer;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Rish
 */
public class Cus_Packages extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cus_Packages
     */
    public Cus_Packages() {
        initComponents();
        
        try{
            //add the details to the table by calling the method from the customer class
        packages.setModel(DbUtils.resultSetToTableModel(Customer.viewPackages()));
       
        
        }
        catch(Exception e){
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        packages = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(541, 370));

        packages.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Package_No", "Name", "Description", "Price"
            }
        ));
        jScrollPane1.setViewportView(packages);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable packages;
    // End of variables declaration//GEN-END:variables
}
