/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Customer;


import EntityPackage.Customer;
import net.proteanit.sql.DbUtils;
import java.sql.ResultSet;

/**
 *
 * @author Rish
 */
public class Cus_MainCourses extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cus_MainCourses
     */
    public Cus_MainCourses() {
        initComponents();
        
        try{
            //add the details to the table by calling the method from the customer class
        
            ResultSet res = Customer.viewItems("main_courses");
        //    res.next();
            maincourses.setModel(DbUtils.resultSetToTableModel(res));
       
        
        }
        catch(Exception e){
        
        }
    }
        
      
            //   item.setModel(DbUtils.resultSetToTableModel(rs));
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        maincourses = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(541, 370));

        maincourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item_No", "Name", "Description", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(maincourses);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable maincourses;
    // End of variables declaration//GEN-END:variables
}
